/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rekhamittal' at '5/14/15 11:03 AM' with Gradle 2.3
 *
 * @author rekhamittal, @date 5/14/15 11:03 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
